modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"
issueTrackerURL = "https://github.com/terrarium-earth/Tempad/issues"

[[mods]]
modId = "tempad"
version = "${version}"
displayName = "Tempad"
displayURL = "https://modrinth.com/mod/tempad"
logoFile = "icon.png"
authors = "CodexAdrian"
credits = "MsRandom1, ThatGravyBoat, Kekie6, AlexNijjar, ShrimpPixels, Jooosh, abused_master"
description = "Create a portal to anywhere from anywhere!"

[[mixins]]
config = "tempad-common.mixins.json"

[[mixins]]
config = "tempad.mixins.json"

[[dependencies.tempad]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"
